### ISSUE TITLE
PV inverter not shown

### ISSUE THREAD

**Issue by wasn-eu** [mr-manuel/venus-os_dbus-mqtt-pv#10]
Hello,

i installed your dbus-mqtt tools to my raspberry pi 4 running venus OS large v3.0.1
all other implementations are shown but not the pv inverter.
in the setting i can see it:
![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/6542516/ec175020-b506-465f-9c2f-70252f46c8f9)

But in the graphical overview it is not shown:
![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/6542516/9220e00b-a4e4-4b72-a2c0-743352e00bdd)

please help

**Comment by mr-manuel** [comment]
Try to change this:

https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/blob/a3af5ae1d0372fb9d3859a1dd6d2ee301937b59c/dbus-mqtt-pv/config.sample.ini#L34-L38

**Comment by wasn-eu** [comment]
that position=0 is the default
i changed it to position=1 and now it ist shown.

thank you for the fast help
