### ISSUE TITLE
wrong calaculation

### ISSUE THREAD

**Issue by wasn-eu** [mr-manuel/venus-os_dbus-mqtt-pv#11]
Hello

why show the ac load widget the same value as the pv inverter widget when there is a negative powef in ac input?
![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/6542516/919c658c-b5a4-4684-8c6a-1f974f554943)

the ac loads power value of the  phase should be pv inverter value + ac input value
for example: on phase 3
  pv inverter power: 340W
  ac input power: -67W
that should be:
  ac loads: 273W

because i send 67W back to the grid

**Comment by wasn-eu** [comment]
if i have a positive power for L3 the calculation ist correct:
![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/6542516/e99bd925-99af-4501-b117-a60db3ac087c)

the pv inverter power and ac input power in sum is the ac loads power

**Comment by mr-manuel** [comment]
The `dbus-mqtt-pv` does not make any calculations. This is because of the `dbus-systemcalc-py` from Victron and the fact that you don't have a MultiPlus.
Try to use the [`dbus-multiplus-emulator`](https://github.com/mr-manuel/venus-os_dbus-multiplus-emulator) from my repository.

**Comment by wasn-eu** [comment]
i have now installed the multiplus-emulator and get this:
![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/6542516/f90fcea7-86b0-43f1-8945-78542df4eab5)

the AC input on L3 is correct but the AC loads on L3 is allways 0 it should be: grid l3 -  pv l3
can i configure the emulator for that?

**Comment by wasn-eu** [comment]
perhabs you can disable the critital loads?

**Comment by mr-manuel** [comment]
Try to change the position of the PV to `0` again.

https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/blob/a3af5ae1d0372fb9d3859a1dd6d2ee301937b59c/dbus-mqtt-pv/config.sample.ini#L34-L38

**Comment by wasn-eu** [comment]
it is now on position=0 but without a change:
looks a little different cause i just installed the gui mods:

![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/6542516/f108d638-6e96-4caa-abb3-ded4a3a3ad65)

**Comment by wasn-eu** [comment]
it must be the emulator.
when i uninstall it it get this:
![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/6542516/e2366ac4-1597-4140-8b21-c11f6e268e8f)

this is right.
the sum of grid L3 and PV L3 are the Loads L3

**Comment by mr-manuel** [comment]
With GuiMods it gets displayed in another way. So now it‘s displayed correctly?

**Comment by wasn-eu** [comment]
yes now it is correct
