### ISSUE TITLE
PV Inverter before and behind Multiplus

### ISSUE THREAD

**Issue by mapchen** [mr-manuel/venus-os_dbus-mqtt-pv#19]
Hello,

I have added 2 inverters with the help of this plugin. Works pretty good. One of the inverter is before the multiplus setup the other is behind. Therefore I used the different positions available in the config file:

 1 = AC output
 2 = AC input 2

What i can see is that the statistics like total Energy a day looks correct. Only for the visualisation of power i can only see the Inverter behind multiplus.

Is there a way to show two different boxes in VRM like this?
![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/56200461/ab219f69-3dd8-4173-934b-179988802c5e)

**Comment by mr-manuel** [comment]
Please ask this question to the Victron Community.
