### ISSUE TITLE
Wechselrichter nur an L2, dann teils unplausible Werte und Ansichten

### ISSUE THREAD

**Issue by mentos77** [mr-manuel/venus-os_dbus-mqtt-pv#20]
Hallo Marcel, 
nutze seit paar Tagen dein Script, um die Daten vom Wechselrichter (erfasst mit OpenDTU) in Venus OS (auf Cerbo GX, v3.13) einzulesen und darzustellen. Mein Wechselrichter ist an L2 angeschlossen, demzufolge schicke ich auch nur Daten für L2, wie auf nachfolgenden „Dummydaten“ zu sehen:
![mqtt msg](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/43184163/a6a850bf-6e5f-4b8e-99dc-19be26d278b5)
In Venus OS (Detailansicht von diesem Gerät) werden jedoch identische Daten sowohl bei L1 als auch L2 angezeigt, bei L3 nur Bindestriche, was ja auch richtig ist. 
![ansicht 1](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/43184163/7879e31e-a46c-4798-81dd-4d196a71f1d3)

In der Übersicht
![ansicht 2](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/43184163/8bda7334-8b0f-49bf-9211-c4361d63b792)

und Kachelansicht aber die Summe beider Phasen (also hier 2W).
![ansicht 5](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/43184163/91423617-7bab-4dc0-a489-380fc9281efb)

Denke Ursache dafür ist in dbus-mqtt-pv.py die Zeilen 261-266. 
![ansicht 3](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/43184163/10c4cda5-8319-43b9-a652-e5d8b3b06089)

Kommentiere ich diese aus, werden nur noch Werte bei L2 und AC Gesamt angezeigt (jeweils 1W). Bei L1 stehen alle Werte auf 0, bei L3 sind weiterhin Bindestriche zu sehen. 
![ansicht 12](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/43184163/217072a7-b973-486d-a15c-7b5afabe9f79)

In den Übersichten wird die richtige Gesamtleistung von 1W angezeigt.
![ansicht 6](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/43184163/4ab06c19-3d90-4d30-8b4b-eee7c48a136d)
![ansicht 7](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/43184163/084aca1e-60b2-4b78-8714-d5ac55e15d24)

Das bei L1 weiterhin etwas angezeigt wird (0-Werte) liegt wohl an den Zeilen 392-396. 
![ansicht 8](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/43184163/53d5e37f-0d7d-4883-a6a6-b7969419d611)

Kommentiere ich diese ebenfalls aus, wird in der Detailansicht alles wie gewünscht angezeigt, sprich die richtigen Werte (1W bei L2 und AC Gesamt), bei L1 und L3 nur Bindestriche. 
![ansicht 9](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/43184163/940d2c6e-5c84-4eba-b52e-c8a9807cf790)

In der Übersicht gibt es eine Anzeige für den PV-Wechselrichter, auch mit dem richtigen Wert von 1W.
![ansicht 11](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/43184163/64ef3250-f00a-4dfb-97b3-2bad2bbee51b)

Allerdings wird in der Kachelansicht gar kein PV-Wechselrichter mehr angezeigt. Die entsprechende Kachel zeigt das Victron Logo. 
![ansicht 10](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/43184163/922cb248-9e27-4e3d-b455-42a4c8bfd0ff)

Hast du eine Idee wie man das so hinbekommt, das überall das gewünschte angezeigt wird?
Danke und Gruß
Mentos77

**Comment by mr-manuel** [comment]
Hallo @mentos77,

leider weiß ich nicht wen du mit Marcel meinst :-)

Ich habe den Treiber aktualisiert, kannst du er mit der letzten Version erneut versuchen?

**Comment by mentos77** [comment]
Hallo Manuel,
sorry das ich den falschen Namen benutzt habe.
Habe den aktualisierten Treiber nun kurz getestet. Sieht soweit gut aus, Werte kommen nun richtig bei L2 an und auch beim Rest steht nix blödsinniges mehr. Mit anderen Phasen, auch in verschiedenen Kombinationen, funktioniert es auch.
Das Einzige, was noch nicht geht ist die Anzeige bei den Kacheln. Aber da mir diese Anzeige eh nicht gefällt ist es für mich kein weiteres Problem mehr.
Vielen Dank für das Update.
Gruß
Mentos77

**Comment by mr-manuel** [comment]
Wichtig ist, dass es mit der GUIv2 funktioniert.
