### ISSUE TITLE
energy_forward provided via mqtt, expected as total or reset every day, or delta since last message?

### ISSUE THREAD

**Issue by dyn4mic** [mr-manuel/venus-os_dbus-mqtt-pv#21]
as title says, clarification on how energy_forward shall be provided.
shall it start daily at zero and sum up until end of day?
shall it have the total energy produced by the inverter since start?
shall it hold the energy produced since last message?

Thanks for clarification

**Comment by mr-manuel** [comment]
It's the lifetime production of the inverter.

**Comment by dyn4mic** [comment]
thanks for clarification
