### ISSUE TITLE
VRM display with pv inverter MQTT

### ISSUE THREAD

**Issue by zigomatichub** [mr-manuel/venus-os_dbus-mqtt-pv#24]
Hello,
I'm in the configuration (multiplus II) with the green part as solar injection and I added the mqtt to retrieve the information towards venus.
![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/60198279/60c70f77-e9c1-4f5d-b253-985932c7a66b)
But when I look into VRM, it's not at the good place.
I tried all the positions of the config but this is always at same place or not visible.
![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/60198279/a6592a98-ea8e-4b43-a2b9-bfe8a61a1a70)

I have a clamp on the grid which is connected to multiplus (ext-com instead of internal clamp).
In other to get correct grid calculation, position 1 is needed which seems weird. 

Is it possible or it's not available from venus ?
Do I do something wrong ?

**Comment by mr-manuel** [comment]
Please check the Remote Console, if the placement is correct.

**Comment by mr-manuel** [comment]
Ok, you are using GuiMods, therefore the correct position is not shown. Use position 1, even it it's not displaying correct.

For Enphase you are able to get real time data. Check [venus-os_dbus-enphase-envoy](https://github.com/mr-manuel/venus-os_dbus-enphase-envoy).

**Comment by zigomatichub** [comment]
Thank you for your reply and suggestion
