### ISSUE TITLE
timeout=0 doesn´t work in new version?

### ISSUE THREAD

**Issue by kr0815** [mr-manuel/venus-os_dbus-mqtt-pv#25]
As one of my inverters is connected to L2i had problems with the shown AC-loads / dbus-mqtt reports them as L1

I saw there is a new version now that reflects that problem

But there must be a bug
i have timeout=0

Directly after i start the program i get:

`INFO:root:MQTT client: Connecting to broker 192.168.178.47 on port 1883
INFO:root:Waiting 5 seconds for receiving first data...
INFO:root:MQTT client: Connected to MQTT broker!
ERROR:root:Driver stopped. Timeout of 0 seconds exceeded, since no new MQTT message was received in this time.
root@raspberrypi2:/data/etc/dbus-mqtt-pv3#
`

**Comment by mr-manuel** [comment]
The `timeout = 0` is only working, if the driver is already running. If the driver has no data it cannot start and is trying to start until he gets some data.
