### ISSUE TITLE
Odd readings

### ISSUE THREAD

**Issue by jeedee5** [mr-manuel/venus-os_dbus-mqtt-pv#26]
Hi,

I installed the MQTT driver on my CerboGX, that is monitoring the PV's, but once it starts receiving data, the grid values on my victron starts acting up...

Following is my MQTT topic data
meter/pv {"pv": {"power": 6114.9, "L1": {"power": 0.0, "voltage": 231.9}, "L2": {"power": 3090.2, "voltage": 231.9}, "L3": {"power": 3024.7, "voltage": 231.9}}}

Without the MQTT meter:
![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/4850169/3a34c2b2-b187-4bed-99fb-0ab68d3fcdb3)

Once the meter is reading data, I suddenly have a lot more energy going to the grid.
![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/4850169/91853d89-0d79-4c55-b798-0c540d3e5bcb)

In addition , there is also no animation on the pv meter to show the energy flow direction

**Comment by mr-manuel** [comment]
Your system is already wrong before. Why are the loads always 0?

**Comment by mr-manuel** [comment]
Since this is a setup issue please check the Victron Community, which is the right place for your question.

**Comment by jeedee5** [comment]
Fixed it... 

in the config.ini, i needed to change the position of the mqtt reader, so that is configured on the AC-output (while in reality it is on the AC-input)
; position (connected input/output) of the PV inverter
; 0 = AC input 1 (select this if you don't have a MultiPlus or Quattro)
; 1 = AC output
; 2 = AC input 2
position = 1

![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/4850169/be2d0998-daec-47d6-b9dd-07b9cfef2570)
