### ISSUE TITLE
Changing Position of inverter in GUI

### ISSUE THREAD

**Issue by konus1** [mr-manuel/venus-os_dbus-mqtt-pv#27]
Hello I use my Multiplus in two different Modi (with a bypass switch). Do you know an easy way to change the Position Value of the Inverter an the Cerbo via GUI?

**Comment by mr-manuel** [comment]
At the moment this was not planned via the driver itself. Anyway you can change the value by sending an MQTT payload to the dbus topic. See https://github.com/victronenergy/dbus-flashmq

**Comment by konus1** [comment]
Thank you for sending me in the right direction!
