### ISSUE TITLE
PV Power needs to be negative for proper energy accounting

### ISSUE THREAD

**Issue by fred777** [mr-manuel/venus-os_dbus-mqtt-pv#29]
This should be noted in the readme: PV power must have a negative sign for proper accounting.

With positive power the computed consumption / AC-Load will be wrong, also in VRM portal:

![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/5749774/823d5604-a6bb-44f1-b5c4-054dd20cb9a3)

And with negative power - as it is done with any other power source like battery discharge - the computed consumption is correct:

![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/5749774/d02e1373-9c95-4abd-bdf0-e002c515b25c)

**Comment by mr-manuel** [comment]
PV power cannot be negative. You probably have a configuration error.
