### ISSUE TITLE
Root Exception Error

### ISSUE THREAD

**Issue by blackpearlla** [mr-manuel/venus-os_dbus-mqtt-pv#3]
Hi,

what does this Error mean exactly? I dont know what im doning wrong..?!

ERROR:root:Exception occurred: argument of type 'int' is not iterable

**Comment by blackpearlla** [comment]
after a reinstallation it works. i dont know whats happening...

**Comment by mr-manuel** [comment]
Can you send me the JSON you send over MQTT? Normally the error means that the variable is a number instead of a list.
