### ISSUE TITLE
Position not recognized

### ISSUE THREAD

**Issue by Piranha1511** [mr-manuel/venus-os_dbus-mqtt-pv#33]
Hi,

I'm running two instances of the driver for two different PV-Inverter. One is configured with position = 0 for AC-IN and the other one is configured with position = 1 for AC-OUT.

But both inverters are visualized in Venus as one with the sum of both. Same in VRM Online portal.
<img width="522" alt="Bildschirmfoto 2024-07-06 um 12 46 31" src="https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/6705464/101d6f6e-d3ba-4cbe-9f61-1100a611ce40">
<img width="523" alt="Bildschirmfoto 2024-07-06 um 12 46 38" src="https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/6705464/ae1648d5-2aa3-4b8c-beb3-1a4b94f1dd93">

I expected that one is shown on AC-IN and the other on AC-Out. Like this:

![39671-victron](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/6705464/c5c5a0f2-0426-4f8f-a174-7098492bf29c)

**Comment by mr-manuel** [comment]
It seems that you don't have a MultiPlus or Quattro. This is a requirement to make it work.
