### ISSUE TITLE
Total solar faulty

### ISSUE THREAD

**Issue by SEWADE** [mr-manuel/venus-os_dbus-mqtt-pv#34]
Hello,

I'm desperately trying to integrate my SOLAX inverter into Venus correctly.

![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/31615609/78035a00-d1ea-49fa-b8fb-44c16e143b59)
![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/31615609/717ae160-49bb-4dee-9e65-e69aba3cb365)
![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/31615609/236be761-de20-4394-b8b0-863ebf4a1cf1)
![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/31615609/95bcdf68-6be3-4485-b303-ed22178a5820)

`root@raspberrypi2:~# cat /data/etc/dbus-mqtt-pv/config.ini`

```ini
; CONFIG FILE
; GitHub reporitory: https://github.com/mr-manuel/venus-os_dbus-mqtt-pv
; remove semicolon ; to enable desired setting

[DEFAULT]
; Set logging level
; ERROR = shows errors only
; WARNING = shows ERROR and warnings
; INFO = shows WARNING and running functions
; DEBUG = shows INFO and data/values
; default: WARNING
logging = WARNING

; Device name
; default: MQTT PV
device_name = SOLAX_X1_5K

; Device VRM instance
; default: 51
device_instance = 51

; Specify after how many seconds the driver should exit (disconnect), if no new MQTT message was received
; default: 60
; value to disable timeout: 0
timeout = 60

; used when no voltage is received
voltage = 230


[PV]
; Max rated power (in Watts) of the inverter
max = 5000
; position (connected input/output) of the PV inverter
; 0 = AC input 1 (select this if you don't have a MultiPlus or Quattro)
; 1 = AC output
; 2 = AC input 2
position = 1


[MQTT]
; IP addess or FQDN from MQTT server
broker_address = 10.0.200.52

; Port of the MQTT server
; default plaintext: 1883
; default TLS port: 8883
broker_port = 1883

; Enables TLS
; 0 = Disabled
; 1 = Enabled
;tls_enabled = 1

; Absolute path to the Certificate Authority certificate file that is to be treated as trusted by this client
;tls_path_to_ca = /data/keys/mosquitto.crt

; Disables verification of the server hostname in the server certificate
; 0 = Disabled
; 1 = Enabled
;tls_insecure = 1

; Username used for connection
;username = myuser

; Password used for connection
;password = mypassword

; Topic where the pv data as JSON string is published
; minimum required JSON payload: {"pv": { "power": 0.0 } }
topic = enphase/envoy-s/meters
root@raspberrypi2:~# 
```

I have now managed to get the PV yield to be displayed and added to the "Total solar".

![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/31615609/df012104-c2c6-4790-a6eb-58f0d0935e62)

Unfortunately, the total PV yield is no longer displayed in the statistics. Only the yield of my two MPPTs is displayed here.

![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/31615609/afa3c3dc-ad33-4f1c-8ad2-6ac0bea6d920)

Perhaps someone has a tip as to what the reason for this is.

Cheers
Sebastian

Edit @mr-manuel: Translated to english

**Comment by mr-manuel** [comment]
You need to provide the `energy_forward` in your JSON, else it won't work. Therefore you need to get the total kWh produced by your PV inverter and pass it to Venus OS.
