### ISSUE TITLE
How to configure AC-In / AC-Out

### ISSUE THREAD

**Issue by endurance1968** [mr-manuel/venus-os_dbus-mqtt-pv#35]
Hi,

for "normal" PV inverters you can configure if they are connected to AC-IN/OUT in Venus.
![image](https://github.com/user-attachments/assets/acccea69-eb07-4ace-ab9a-b86b0b1cfb05)
how can I switch the PV MQTT from AC-IN to AC-Out?

**Comment by mr-manuel** [comment]
Just read the config file...

https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/blob/a837a8593cd06189fe1b3cfcea127eda7ddd8a12/dbus-mqtt-pv/config.sample.ini#L37-L41
