### ISSUE TITLE
Welche Werte muss man denn beschreiben?

### ISSUE THREAD

**Issue by BenAhrdt** [mr-manuel/venus-os_dbus-mqtt-pv#4]
Hallo, ich habe eine MQTT Verbindung.
Welche Werte (Topics) muss ich denn beschreiben, damit ein eine PV-Anlage "emulieren" kann?

**Comment by mr-manuel** [comment]
Hallo,
hast du die README Datei gelesen? Das von dir gewünschte Topic gibst du in der `config.ini` an. Hier ein Beispiel aus der `config.sample.ini`:

https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/blob/b31ca39290db3a66fff84d1da210bfca4bbcc652/dbus-mqtt-pv/config.sample.ini#L69-L71

Die benötigsten Werte findest du unter [JSON structure](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv#json-structure).

**Comment by BenAhrdt** [comment]
ich kann eine topic = enphase/envoy-s/meters  anlegen und den Wert da rein schreiben
{
    "pv": {
        "power": 0.0,
        "L1": {
            "power": 0.0
        }
    }
}

dann erkennt der MP2 GX das direkt?

**Comment by mr-manuel** [comment]
Das Topic kann heißen wie du willst. Ohne den Treiber/Script wird das nicht funktionieren, deshalb gibt es das ja.

Name usw. kannst du alles in der `config.ini` einstellen.

**Comment by BenAhrdt** [comment]
ich will ja das script nicht, sondern die daten aus ioBroker senden.
Irgendwo muss doch bekannt sein, welche Daten den MP2 GX erwartet.
ODER?
Also, ich möchte gerne Name, leistung usw. selbst da hin schicken, kenne nur das notwendige format nicht,
bzw. ob es eine MQTT Konvention gibt seitens VICTRON.
Braucht man ein eigene Topic mit dem Namen, eins mit der Leistung usw.

**Comment by mr-manuel** [comment]
Kann man ja auch, wenn man das Script verwendet. Was spricht dagegen?

**Comment by BenAhrdt** [comment]
ich nutze ioBroker und möchte gerne alles darin machen und nicht noch extern auslagern.
Aber egal, dann muss ich wohl darauf verzichten.
