### ISSUE TITLE
No MQTT Inverter on VenusOS

### ISSUE THREAD

**Issue by Zahnpasta83** [mr-manuel/venus-os_dbus-mqtt-pv#5]
Hello, I installed the tool as described in the instructions but I don't get a mqtt inverter displayed in venusos. 
Debug was carried out and the tool started without any problems. 
Data is sent via the mqtt topic enphase/envoy-s/meters. do i have to do anything else to get the tool to work?

**Comment by Zahnpasta83** [comment]
when looking in the logs i get following message "ERROR:root:Exception occurred: argument of type 'int' is not iterable"

**Comment by mr-manuel** [comment]
Hello, please post the complete log since driver starting and the published JSON.

**Comment by Zahnpasta83** [comment]
Ich hab es irgendwie fertig gebracht das ein MQTT Inverter in Venus auftaucht. Allerdings bin ich offensichtlich nicht in der Lage die Werte die ich in NodeRed bekomme vernünftig in ein JSON Format zu konvertieren. Vielleicht könntest du mir da aushelfen. Ich bekomme reine Zahlenwerte und habe dort eine Change Node dran gehängt. Wie muss ich diese konfigurieren ![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/122221616/34de7491-22fd-4217-9d38-d4cb7aea2f38)

**Comment by mr-manuel** [comment]
Which values do you have available? Only the PV power? Please share the whole flow.

**Comment by Zahnpasta83** [comment]
A lot of trail and error but it's working now ![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/122221616/cd5fe5d8-7ca6-40c3-9f6e-637de3ea8296)

![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/122221616/1a703ea3-ecfd-4a12-abaa-ea51e239abdf)

![image](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv/assets/122221616/df90caea-318e-4fae-a823-2301226c1b98)
